# Check Lua Formatting
name: Check Lua Formatting
on:
    push:
      branches: [ main ]
    pull_request:
      types: [ labeled ]

jobs:
  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.18.0
          # CLI arguments
          args: --check .
