name: Lint
on: [push, pull_request]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '16'
            - name: Lint
              uses: iLLeniumStudios/fivem-lua-lint-action@v2
              with:
                  capture: "junit.xml"
                  args: "-t --formatter JUnit"
                  extra_libs: mysql+ox_lib
            - name: Generate Lint Report
              if: always()
              uses: mikepenz/action-junit-report@v3.7.7
              with:
                  report_paths: "**/junit.xml"
                  check_name: Linting Report
                  fail_on_failure: false