name: Test Suite

on: [push, pull_request]

jobs:
  lint:
    name: Lint Lua scripts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server-data/resources
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: GoatG33k/fivem-lua-lint-action@v1